### ISSUE TITLE
make error，how can this problem be solved?

### ISSUE THREAD

**Issue by q1178847289** [ouceduxzk/Fine_Grained_Classification#7]
../lib/libcaffe.so.1.0.0：对‘caffe::RankLoss2Layer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&)’未定义的引用
../lib/libcaffe.so.1.0.0：对‘caffe::RankLoss2Layer<double>::Backward_gpu(std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&, std::vector<bool, std::allocator<bool> > const&, std::vector<caffe::Blob<double>*, std::allocator<caffe::Blob<double>*> > const&)’未定义的引用

**Comment by ouceduxzk** [comment]
i did not have such problem,  will check it soon

**Comment by q1178847289** [comment]
Will it be caused by the lack of a layer .cu  in the layer file?

**Comment by ouceduxzk** [comment]
yeah, since you have the forward_gpu, then you need to have .cu cuda kernel file. I have uploaded the caffe version that works, no need for a gpu kernel

**Comment by q1178847289** [comment]
I don't know how to write .cu files.but i will try。 Is there any other way to solve this problem?Thank you very much for your patience to help me answer doubts。

**Comment by ouceduxzk** [comment]
check caffe_racnn in this repo, there is a cpp for rank. Basically for loss function, you do not necessaryily need a cu file

**Comment by q1178847289** [comment]
okey，thank you very much ! wish you have a good time.

**Comment by q1178847289** [comment]
Because of an error in the compilation process, it still cannot be solved. How do I compile caffe, is it a caffe that compiles a CPU version? thank you very much!
